{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "owtdtu7bmbejrfvi2goofsjoa4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.4.2.jar",
          "url": "kodein-internal-gradle-plugin-6.4.2.jar",
          "size": 259999,
          "sha512": "530fa744d4829de3a5d15941eec5781b93aaa00ab3e38c307c39c77a3b50cf24f784e6286f9e44b1217d7a63360702495f3cc63d61cefb027b652ad427639a48",
          "sha256": "864840a440cc02097f015e40e3f3c21f4453765ff03a53ba9bdbd43a5582a63c",
          "sha1": "9d3e81e9fc09766b100c3d8bcd1fbd6e954f5055",
          "md5": "c0f31dbd07961d97006f769ae1aea25c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.4.2.jar",
          "url": "kodein-internal-gradle-plugin-6.4.2.jar",
          "size": 259999,
          "sha512": "530fa744d4829de3a5d15941eec5781b93aaa00ab3e38c307c39c77a3b50cf24f784e6286f9e44b1217d7a63360702495f3cc63d61cefb027b652ad427639a48",
          "sha256": "864840a440cc02097f015e40e3f3c21f4453765ff03a53ba9bdbd43a5582a63c",
          "sha1": "9d3e81e9fc09766b100c3d8bcd1fbd6e954f5055",
          "md5": "c0f31dbd07961d97006f769ae1aea25c"
        }
      ]
    }
  ]
}
