{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.15.0.jar",
          "url": "kodein-internal-gradle-plugin-6.15.0.jar",
          "size": 284003,
          "sha512": "d1e73d69c054062cbf47b3b9313bd215de663ae89500d7c138eac8813321cc886ea4dec8d5a8dd237d70171ac6affed21e38b823373afa93be143676183e6b81",
          "sha256": "5ccada03e0840a42c176b21e1ebe4984dbc2e3288681a786babfdc04878de0c6",
          "sha1": "e2ef28a1f12d3ff5f07728aa94d18c060cb45ff5",
          "md5": "c0f9a65902b61014fb08b0a1e0d67c1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.15.0.jar",
          "url": "kodein-internal-gradle-plugin-6.15.0.jar",
          "size": 284003,
          "sha512": "d1e73d69c054062cbf47b3b9313bd215de663ae89500d7c138eac8813321cc886ea4dec8d5a8dd237d70171ac6affed21e38b823373afa93be143676183e6b81",
          "sha256": "5ccada03e0840a42c176b21e1ebe4984dbc2e3288681a786babfdc04878de0c6",
          "sha1": "e2ef28a1f12d3ff5f07728aa94d18c060cb45ff5",
          "md5": "c0f9a65902b61014fb08b0a1e0d67c1e"
        }
      ]
    }
  ]
}
