{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "g3tcdsjlmje75akwytr2nhnsam"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0-SNAPSHOT.jar",
          "size": 244963,
          "sha512": "88c3c83fd1551fdfeade639ac6084fbe31e3269c7e1a13d563b75327646fc5475f9f588d989d05cb28e7683ef460111d48d81916f126b5b06657136c552ffa8a",
          "sha256": "c362a0508dbe53fb44fa44294c3a6ec36137fd2de2f128d08d70c7bd6bc47ae1",
          "sha1": "03d19900040102ee8a462137f4865609d3882751",
          "md5": "3a5f2738a54fd1149fd2bd1cf67b073f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0-SNAPSHOT.jar",
          "size": 244963,
          "sha512": "88c3c83fd1551fdfeade639ac6084fbe31e3269c7e1a13d563b75327646fc5475f9f588d989d05cb28e7683ef460111d48d81916f126b5b06657136c552ffa8a",
          "sha256": "c362a0508dbe53fb44fa44294c3a6ec36137fd2de2f128d08d70c7bd6bc47ae1",
          "sha1": "03d19900040102ee8a462137f4865609d3882751",
          "md5": "3a5f2738a54fd1149fd2bd1cf67b073f"
        }
      ]
    }
  ]
}
