{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "eocqsoifyzd6rggclifwpbsvia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0-SNAPSHOT.jar",
          "size": 245110,
          "sha512": "d6a4f3e0c06bb71177e3c99a0fe25063edbc2ce2f1ee20bcf87f2d26fdb39d89ffca08a759f6ea4147bdefd17a59abdbf621497efbd6e76bc381b683ab5c7120",
          "sha256": "3de7c4766b679d2d172ae374475e3255ed3a3dab3a91f2de79289dea4659aecb",
          "sha1": "7a854ffb73057aa22cc3cece4ce7aaf8216b71da",
          "md5": "3ec89d5b8709e5cdfbfc78cd7ce9c75e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0-SNAPSHOT.jar",
          "size": 245110,
          "sha512": "d6a4f3e0c06bb71177e3c99a0fe25063edbc2ce2f1ee20bcf87f2d26fdb39d89ffca08a759f6ea4147bdefd17a59abdbf621497efbd6e76bc381b683ab5c7120",
          "sha256": "3de7c4766b679d2d172ae374475e3255ed3a3dab3a91f2de79289dea4659aecb",
          "sha1": "7a854ffb73057aa22cc3cece4ce7aaf8216b71da",
          "md5": "3ec89d5b8709e5cdfbfc78cd7ce9c75e"
        }
      ]
    }
  ]
}
