{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wyusjgozefeglixi5tzrybulf4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0.jar",
          "url": "kodein-internal-gradle-versions-6.0.0.jar",
          "size": 3147,
          "sha512": "687e75795c3c65042797e1182ee71fbad3047330fb8122fa88289ab89cada7e3b0b2cb4c902e0794af53eeb29e838451dbc857eeb49492adf6196784cc296e5c",
          "sha256": "3ee244156cbb7828b05003cd93a115672b519c2d6bfcb583bc4fbf00c947543f",
          "sha1": "ecf18c14875147fa9d38c935f5b946b5aac5ea13",
          "md5": "09f0dee1991d3c47daf5cccbdfee9bc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0.jar",
          "url": "kodein-internal-gradle-versions-6.0.0.jar",
          "size": 3147,
          "sha512": "687e75795c3c65042797e1182ee71fbad3047330fb8122fa88289ab89cada7e3b0b2cb4c902e0794af53eeb29e838451dbc857eeb49492adf6196784cc296e5c",
          "sha256": "3ee244156cbb7828b05003cd93a115672b519c2d6bfcb583bc4fbf00c947543f",
          "sha1": "ecf18c14875147fa9d38c935f5b946b5aac5ea13",
          "md5": "09f0dee1991d3c47daf5cccbdfee9bc2"
        }
      ]
    }
  ]
}
