{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ayimeqlslnajnkcs2l5mgvkplm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0.jar",
          "url": "kodein-internal-gradle-versions-6.0.0.jar",
          "size": 3147,
          "sha512": "993a8e8df7331b0f94eeae5648c793080c547b94272df4b9aa435f353769a62a2c4e99c1919e07be38d4c54d38fded4a6a329416cdb65dad14c06e68bbba1ac2",
          "sha256": "ea51ae2b09189e56723436e26d17a000eb95dd0676f2f40437e0076054450825",
          "sha1": "dae985a46b3aa3b4f87f6b762f020ad5b15fcc90",
          "md5": "6b82fcdc081d4bd0161ca42a4dad1157"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0.jar",
          "url": "kodein-internal-gradle-versions-6.0.0.jar",
          "size": 3147,
          "sha512": "993a8e8df7331b0f94eeae5648c793080c547b94272df4b9aa435f353769a62a2c4e99c1919e07be38d4c54d38fded4a6a329416cdb65dad14c06e68bbba1ac2",
          "sha256": "ea51ae2b09189e56723436e26d17a000eb95dd0676f2f40437e0076054450825",
          "sha1": "dae985a46b3aa3b4f87f6b762f020ad5b15fcc90",
          "md5": "6b82fcdc081d4bd0161ca42a4dad1157"
        }
      ]
    }
  ]
}
