{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "izzhweihtnanni3haviszdo7z4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0.jar",
          "url": "kodein-internal-gradle-versions-6.0.0.jar",
          "size": 3147,
          "sha512": "8e3bac2a28f6e660b2ee8da034a2a70934a7139a4968c0ea90fdc85de23f0787ca189c02566252d876428697bc2f027175ac19f3eeb4fb252a3efb1a02c25642",
          "sha256": "d3af3d08a8518ebcc3a47564cd55c893489f86b3cea88214750361768dfc2e04",
          "sha1": "466d2afeb7bc206b6fe8b61d988e15af742be938",
          "md5": "0cfaae624adcf217403e609fa1f37150"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0.jar",
          "url": "kodein-internal-gradle-versions-6.0.0.jar",
          "size": 3147,
          "sha512": "8e3bac2a28f6e660b2ee8da034a2a70934a7139a4968c0ea90fdc85de23f0787ca189c02566252d876428697bc2f027175ac19f3eeb4fb252a3efb1a02c25642",
          "sha256": "d3af3d08a8518ebcc3a47564cd55c893489f86b3cea88214750361768dfc2e04",
          "sha1": "466d2afeb7bc206b6fe8b61d988e15af742be938",
          "md5": "0cfaae624adcf217403e609fa1f37150"
        }
      ]
    }
  ]
}
