{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "izzhweihtnanni3haviszdo7z4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0.jar",
          "url": "kodein-internal-gradle-settings-6.0.0.jar",
          "size": 16410,
          "sha512": "dc14a28c0fdd2bff3defb764045f4f0f62ba90737762bc572769d30c93ae055e2cf4db1e9bacd7eb9016c61f51cd7904b5f6a55eae1e232cec003c15608d93bf",
          "sha256": "c0efcc0ad8547343112e358ed7291e6f0533a0ba93c6c8700dc532e2c05ef3fa",
          "sha1": "92b4743ad71aaf04e10560cc2f01416c7d02091a",
          "md5": "1f4470106146ac115bc1c0a4fa728356"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0.jar",
          "url": "kodein-internal-gradle-settings-6.0.0.jar",
          "size": 16410,
          "sha512": "dc14a28c0fdd2bff3defb764045f4f0f62ba90737762bc572769d30c93ae055e2cf4db1e9bacd7eb9016c61f51cd7904b5f6a55eae1e232cec003c15608d93bf",
          "sha256": "c0efcc0ad8547343112e358ed7291e6f0533a0ba93c6c8700dc532e2c05ef3fa",
          "sha1": "92b4743ad71aaf04e10560cc2f01416c7d02091a",
          "md5": "1f4470106146ac115bc1c0a4fa728356"
        }
      ]
    }
  ]
}
