{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ayimeqlslnajnkcs2l5mgvkplm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0.jar",
          "url": "kodein-internal-gradle-settings-6.0.0.jar",
          "size": 16410,
          "sha512": "16bd09001d010b1a31f6526efef686038b4831f37b49bd6697ed949ab72cf32ee637cf967555f55e0703855e60c3b80279ef30f5a8eb571a7b5f45b92bc416f4",
          "sha256": "5996d7876ab71cc4ae083b64685278a1a23cd914294fcfa53a2568cd611848e5",
          "sha1": "4587c6629d19c01c18115de5367ca0eeaf839163",
          "md5": "24eb938309dfb34f856bd3d15d3c3ea0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0.jar",
          "url": "kodein-internal-gradle-settings-6.0.0.jar",
          "size": 16410,
          "sha512": "16bd09001d010b1a31f6526efef686038b4831f37b49bd6697ed949ab72cf32ee637cf967555f55e0703855e60c3b80279ef30f5a8eb571a7b5f45b92bc416f4",
          "sha256": "5996d7876ab71cc4ae083b64685278a1a23cd914294fcfa53a2568cd611848e5",
          "sha1": "4587c6629d19c01c18115de5367ca0eeaf839163",
          "md5": "24eb938309dfb34f856bd3d15d3c3ea0"
        }
      ]
    }
  ]
}
