{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wyusjgozefeglixi5tzrybulf4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0.jar",
          "url": "kodein-internal-gradle-settings-6.0.0.jar",
          "size": 16410,
          "sha512": "25f144dd3c9e71334232cc5ef0d2001add78a89238413e3484e3aac10142d41dc03f8a9f47c2b378868dd7789029236da4fe7fea1ff535b3b447a1e0da673d2b",
          "sha256": "5e856f2c2965f40b76a973ec88d90055baad6948350df7a5feab73845b9bd65e",
          "sha1": "0e45b20983309800162499abc030eb238dbb9d84",
          "md5": "a2ed4b5a7c22a4d9bac32021d9148d1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0.jar",
          "url": "kodein-internal-gradle-settings-6.0.0.jar",
          "size": 16410,
          "sha512": "25f144dd3c9e71334232cc5ef0d2001add78a89238413e3484e3aac10142d41dc03f8a9f47c2b378868dd7789029236da4fe7fea1ff535b3b447a1e0da673d2b",
          "sha256": "5e856f2c2965f40b76a973ec88d90055baad6948350df7a5feab73845b9bd65e",
          "sha1": "0e45b20983309800162499abc030eb238dbb9d84",
          "md5": "a2ed4b5a7c22a4d9bac32021d9148d1b"
        }
      ]
    }
  ]
}
