{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "5.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "kszkwtz4nfgmnalums26egwgby"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.3.2.jar",
          "url": "kodein-internal-gradle-plugin-5.3.2.jar",
          "size": 250757,
          "sha512": "c799172168843d8df172a9211c0dd4b3bed88738a104eb9bde885f1ed76de98ce4e5ec1d98e6a0974b991dc208b46f1877154b329b3e7f4ab994b7f1461c0611",
          "sha256": "ae8535109e102fa8c6a0a7698535299333ab20fa50d8e8536601f98304fd6d6c",
          "sha1": "7be9cf0b2473519b8df36a92bef9e3e51fac0fc1",
          "md5": "82018b5fe64db04243f8d1405b8257cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.3.2.jar",
          "url": "kodein-internal-gradle-plugin-5.3.2.jar",
          "size": 250757,
          "sha512": "c799172168843d8df172a9211c0dd4b3bed88738a104eb9bde885f1ed76de98ce4e5ec1d98e6a0974b991dc208b46f1877154b329b3e7f4ab994b7f1461c0611",
          "sha256": "ae8535109e102fa8c6a0a7698535299333ab20fa50d8e8536601f98304fd6d6c",
          "sha1": "7be9cf0b2473519b8df36a92bef9e3e51fac0fc1",
          "md5": "82018b5fe64db04243f8d1405b8257cb"
        }
      ]
    }
  ]
}
