{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.6.1.jar",
          "url": "kodein-internal-gradle-plugin-8.6.1.jar",
          "size": 444676,
          "sha512": "6f04e0e1e2cf66f616cd3280d71122f55ff9063e897c61e42f280f0b135c46c172225350d9289a73aebfcea57608203cee80a33e4da83476a389d67244f7930f",
          "sha256": "b9b6733b06a5c08db6916bcac85206a5e4c1b6d08e50b304892cb74ed6b11a9b",
          "sha1": "e4497c1d4b18e3e71c9b24e8c270bd08385158f6",
          "md5": "67513dc1cdf94f20d31b08082ebd7b26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.6.1.jar",
          "url": "kodein-internal-gradle-plugin-8.6.1.jar",
          "size": 444676,
          "sha512": "6f04e0e1e2cf66f616cd3280d71122f55ff9063e897c61e42f280f0b135c46c172225350d9289a73aebfcea57608203cee80a33e4da83476a389d67244f7930f",
          "sha256": "b9b6733b06a5c08db6916bcac85206a5e4c1b6d08e50b304892cb74ed6b11a9b",
          "sha1": "e4497c1d4b18e3e71c9b24e8c270bd08385158f6",
          "md5": "67513dc1cdf94f20d31b08082ebd7b26"
        }
      ]
    }
  ]
}
