{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.7.0.jar",
          "url": "kodein-internal-gradle-plugin-6.7.0.jar",
          "size": 256387,
          "sha512": "d9c1bde4cf89582dd509c4c38d5892f8985758f811c03fdf4a0997e7072367c8f4e41bafdf42e2529d21eaa89d0c19ff0441e9a4c1e3581689d29b3bc4bd4419",
          "sha256": "0deda02fe8229d5626a36a8d55ae0061641466d3b342bf907b07ca27838ae288",
          "sha1": "57a915792bca0e73ecbfad14f23e39a7e9e17976",
          "md5": "47c6f46e14fbae228c4dfca9d24e2dd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.7.0.jar",
          "url": "kodein-internal-gradle-plugin-6.7.0.jar",
          "size": 256387,
          "sha512": "d9c1bde4cf89582dd509c4c38d5892f8985758f811c03fdf4a0997e7072367c8f4e41bafdf42e2529d21eaa89d0c19ff0441e9a4c1e3581689d29b3bc4bd4419",
          "sha256": "0deda02fe8229d5626a36a8d55ae0061641466d3b342bf907b07ca27838ae288",
          "sha1": "57a915792bca0e73ecbfad14f23e39a7e9e17976",
          "md5": "47c6f46e14fbae228c4dfca9d24e2dd1"
        }
      ]
    }
  ]
}
