{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ezkxwbevpnd6vp7ramecu7cn4q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.5.1.jar",
          "url": "kodein-internal-gradle-plugin-6.5.1.jar",
          "size": 259845,
          "sha512": "3ab7065d05f5e5a538597cfc567f069e77c1ce272a3780284ddceea5a7ec669e0097634c86433a56e05b9b52a0ca458794b2843d53785f90ec6447d2b61bf2f6",
          "sha256": "35a489b9b8e53c00e41223c6e9c3cef5aa2715b4da33200e1fa23c1f619b8107",
          "sha1": "69df9c2dbbaf05005fcf30a138ebb415dcdbc7b7",
          "md5": "ec3bd1a55853152124387db6dd1a557d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.5.1.jar",
          "url": "kodein-internal-gradle-plugin-6.5.1.jar",
          "size": 259845,
          "sha512": "3ab7065d05f5e5a538597cfc567f069e77c1ce272a3780284ddceea5a7ec669e0097634c86433a56e05b9b52a0ca458794b2843d53785f90ec6447d2b61bf2f6",
          "sha256": "35a489b9b8e53c00e41223c6e9c3cef5aa2715b4da33200e1fa23c1f619b8107",
          "sha1": "69df9c2dbbaf05005fcf30a138ebb415dcdbc7b7",
          "md5": "ec3bd1a55853152124387db6dd1a557d"
        }
      ]
    }
  ]
}
