{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "3.6.0-1.4-M2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jp2gmrascbbgfesfpqxfb7zq4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.6.0-1.4-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4-M2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "0.9.18"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-3.6.0-1.4-M2.jar",
          "url": "kodein-internal-gradle-plugin-3.6.0-1.4-M2.jar",
          "size": 252190,
          "sha512": "db7bed6b23c9b8da27ea9d57b3a1dd4e88dd606ed5df55a8a4c346b5cfc4eb6915375d0c5b1d6a71d8b54e257e45aa8ee1ff651d25b4ddcec2cd5951b979c9c7",
          "sha256": "03b31da1248314f87926b49512f09f24603b82d3a3d76ede36a21ca09af6f2f0",
          "sha1": "e1b083c37a3d345213b955e2222174127630cd53",
          "md5": "d054a9fd85eccac014c6e7956fd51668"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.6.0-1.4-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4-M2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "0.9.18"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-3.6.0-1.4-M2.jar",
          "url": "kodein-internal-gradle-plugin-3.6.0-1.4-M2.jar",
          "size": 252190,
          "sha512": "db7bed6b23c9b8da27ea9d57b3a1dd4e88dd606ed5df55a8a4c346b5cfc4eb6915375d0c5b1d6a71d8b54e257e45aa8ee1ff651d25b4ddcec2cd5951b979c9c7",
          "sha256": "03b31da1248314f87926b49512f09f24603b82d3a3d76ede36a21ca09af6f2f0",
          "sha1": "e1b083c37a3d345213b955e2222174127630cd53",
          "md5": "d054a9fd85eccac014c6e7956fd51668"
        }
      ]
    }
  ]
}
