{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "sjxprfn2vzhxtgaip3hvwv776i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "size": 16350,
          "sha512": "0f3d170b44676024629a8bf08b0a530c60974928b8afe056a1f09956bf8bcb5990389d493a1cfcd1cdb3ebba4ec9842f1301cb0e316542dcd5436a1bac4d01c0",
          "sha256": "e13ea5c1f8f409178103db48e48468e085d100a786862d291842025aedf5d15f",
          "sha1": "d60b608eae4bc7ea4bd47afd79c707c9c7ac9f07",
          "md5": "893cb8aee14e419da8b1b52dedaa4525"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "size": 16350,
          "sha512": "0f3d170b44676024629a8bf08b0a530c60974928b8afe056a1f09956bf8bcb5990389d493a1cfcd1cdb3ebba4ec9842f1301cb0e316542dcd5436a1bac4d01c0",
          "sha256": "e13ea5c1f8f409178103db48e48468e085d100a786862d291842025aedf5d15f",
          "sha1": "d60b608eae4bc7ea4bd47afd79c707c9c7ac9f07",
          "md5": "893cb8aee14e419da8b1b52dedaa4525"
        }
      ]
    }
  ]
}
