{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "xwdpyoo7qzewvns6u354jp5ofu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "size": 16350,
          "sha512": "c58302b7ad096b7b31ee4ac34c4845b754c139a571dcead21ff1aaa3dffdf4dfae5c8ce5efda84fd4a3da5c59a2e08b94166d0ab09c8058788ae72839877119d",
          "sha256": "d067225d5cb6cc23892a3222772dbb2ee6f71d1d02642f6b50503c03ce533af3",
          "sha1": "4b21125a6f77d3e69b4a8312513f3b8d6b69c916",
          "md5": "217d9bbfa5fffe0960e6d986349e4845"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "size": 16350,
          "sha512": "c58302b7ad096b7b31ee4ac34c4845b754c139a571dcead21ff1aaa3dffdf4dfae5c8ce5efda84fd4a3da5c59a2e08b94166d0ab09c8058788ae72839877119d",
          "sha256": "d067225d5cb6cc23892a3222772dbb2ee6f71d1d02642f6b50503c03ce533af3",
          "sha1": "4b21125a6f77d3e69b4a8312513f3b8d6b69c916",
          "md5": "217d9bbfa5fffe0960e6d986349e4845"
        }
      ]
    }
  ]
}
