{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "kpdjtamzgve5bfvfubu7zrysxu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "size": 16350,
          "sha512": "64a9491a0e8507db4baf2c72e331225454827277709c9f64273364e5dff63bf94055e60c9436e52c6e968430a31eb1d4f112720b93e66da96f0f317d4b51f807",
          "sha256": "476616a2822fb69c0a717391e4a0edf15dadfe68d748d7b96fc47ee7b81e0d3f",
          "sha1": "0424bd629130e768fd5335a6f466aab24fbbcac8",
          "md5": "073b945710d7b5b202dfd0d931d83430"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.0.0-SNAPSHOT.jar",
          "size": 16350,
          "sha512": "64a9491a0e8507db4baf2c72e331225454827277709c9f64273364e5dff63bf94055e60c9436e52c6e968430a31eb1d4f112720b93e66da96f0f317d4b51f807",
          "sha256": "476616a2822fb69c0a717391e4a0edf15dadfe68d748d7b96fc47ee7b81e0d3f",
          "sha1": "0424bd629130e768fd5335a6f466aab24fbbcac8",
          "md5": "073b945710d7b5b202dfd0d931d83430"
        }
      ]
    }
  ]
}
