{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.8.0.jar",
          "url": "kodein-internal-gradle-plugin-6.8.0.jar",
          "size": 256862,
          "sha512": "a1950ffaa290608e8940f01ba40740ae85a4d1c2e462d43c1c24c87e9720ca0efd8c2c90112a6a899b1d6a5375e986c22551f6998891c2fcbd50290b92b2eb42",
          "sha256": "2d0065ef7169e617db24ca91a5ac16e195316ccf25bd6846435a9b240e0f68c8",
          "sha1": "97a48cf31f066d35ad113e4e0431398ccd98f6ba",
          "md5": "f0c93273adce3924b4e4b34e68838f16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.8.0.jar",
          "url": "kodein-internal-gradle-plugin-6.8.0.jar",
          "size": 256862,
          "sha512": "a1950ffaa290608e8940f01ba40740ae85a4d1c2e462d43c1c24c87e9720ca0efd8c2c90112a6a899b1d6a5375e986c22551f6998891c2fcbd50290b92b2eb42",
          "sha256": "2d0065ef7169e617db24ca91a5ac16e195316ccf25bd6846435a9b240e0f68c8",
          "sha1": "97a48cf31f066d35ad113e4e0431398ccd98f6ba",
          "md5": "f0c93273adce3924b4e4b34e68838f16"
        }
      ]
    }
  ]
}
