{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "7.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-7.1.0.jar",
          "url": "kodein-internal-gradle-plugin-7.1.0.jar",
          "size": 266570,
          "sha512": "0039ebee3f7de485ca12081b77b35a14eb3e5a1d7a7d0ace2353d2cc0839d0a052120f4fa21e046ada6bde7cb67d097bb947b06b710ebbb72de49e558e62492f",
          "sha256": "3b70959f9ae4608193b1e7c8fb631c256422f5cf7aae9007052086a1d9cad158",
          "sha1": "a61b2a4ffa8f8aefa6874267b42d96ea66bd6da4",
          "md5": "c7587bc44f1c91eeb11a1c6e4a303450"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-7.1.0.jar",
          "url": "kodein-internal-gradle-plugin-7.1.0.jar",
          "size": 266570,
          "sha512": "0039ebee3f7de485ca12081b77b35a14eb3e5a1d7a7d0ace2353d2cc0839d0a052120f4fa21e046ada6bde7cb67d097bb947b06b710ebbb72de49e558e62492f",
          "sha256": "3b70959f9ae4608193b1e7c8fb631c256422f5cf7aae9007052086a1d9cad158",
          "sha1": "a61b2a4ffa8f8aefa6874267b42d96ea66bd6da4",
          "md5": "c7587bc44f1c91eeb11a1c6e4a303450"
        }
      ]
    }
  ]
}
