{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "3.19"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.14.0.jar",
          "url": "kodein-internal-gradle-plugin-8.14.0.jar",
          "size": 435577,
          "sha512": "38713727dea7c78851b2cd7d692aabe8478a6cdfffd4280777cd0c3edbb5e40e3aaf11b34d28faccd30ba2edb6c22654337af1f2a76bc4c22e31adc4080eff07",
          "sha256": "38555c94d15318d654246e417d70ee3f2a80f59414e6e759c76ac0c201bd2c53",
          "sha1": "ad54c0041250446c620a0c129fdfead15c97ab86",
          "md5": "2af9b69cf46cd39258b817f27b882f49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "3.19"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.14.0.jar",
          "url": "kodein-internal-gradle-plugin-8.14.0.jar",
          "size": 435577,
          "sha512": "38713727dea7c78851b2cd7d692aabe8478a6cdfffd4280777cd0c3edbb5e40e3aaf11b34d28faccd30ba2edb6c22654337af1f2a76bc4c22e31adc4080eff07",
          "sha256": "38555c94d15318d654246e417d70ee3f2a80f59414e6e759c76ac0c201bd2c53",
          "sha1": "ad54c0041250446c620a0c129fdfead15c97ab86",
          "md5": "2af9b69cf46cd39258b817f27b882f49"
        }
      ]
    }
  ]
}
