{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.gradleup.nmcp.aggregation",
          "module": "com.gradleup.nmcp.aggregation.gradle.plugin",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "3.19"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.15.1.jar",
          "url": "kodein-internal-gradle-plugin-8.15.1.jar",
          "size": 272079,
          "sha512": "a62c33719f0cba20725b503403c76f4171147aa744cfafa485b5ad782ba392b218d505b72ff9671066c487168e3c81b8e5fc7c28e87538d17ab92b4922731f09",
          "sha256": "6279785a0f7a2d155079e083a20f6bae6af8e5dbba9910b7eb1cb748086d5190",
          "sha1": "26aa44adf085615c3f7d817c20073fd16b847b03",
          "md5": "e51560706299340be07ca97ac2cb4029"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.gradleup.nmcp.aggregation",
          "module": "com.gradleup.nmcp.aggregation.gradle.plugin",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "3.19"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.15.1.jar",
          "url": "kodein-internal-gradle-plugin-8.15.1.jar",
          "size": 272079,
          "sha512": "a62c33719f0cba20725b503403c76f4171147aa744cfafa485b5ad782ba392b218d505b72ff9671066c487168e3c81b8e5fc7c28e87538d17ab92b4922731f09",
          "sha256": "6279785a0f7a2d155079e083a20f6bae6af8e5dbba9910b7eb1cb748086d5190",
          "sha1": "26aa44adf085615c3f7d817c20073fd16b847b03",
          "md5": "e51560706299340be07ca97ac2cb4029"
        }
      ]
    }
  ]
}
