{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "c7k7qfkgp5eetbk5oaqmq57ke4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.1.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.1.0-SNAPSHOT.jar",
          "size": 16410,
          "sha512": "a148b369eb94b773d1ed3defcbe08f6778711fe6cbc838380d7f4fcdfd6484ba830ca819ab9be74fb2fa9c9028f914f8f5d10d4b8f3e9b9f70a58de3391def04",
          "sha256": "3e89184c10099bba074a5b77ec5a29e9fc5a40d2e3a1607565db4756655f2afc",
          "sha1": "55182054b09b4b11ccdcee2cfa61e19d454c197b",
          "md5": "1e1e7707bfde3b4e57bd669e32f2808e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.1.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.1.0-SNAPSHOT.jar",
          "size": 16410,
          "sha512": "a148b369eb94b773d1ed3defcbe08f6778711fe6cbc838380d7f4fcdfd6484ba830ca819ab9be74fb2fa9c9028f914f8f5d10d4b8f3e9b9f70a58de3391def04",
          "sha256": "3e89184c10099bba074a5b77ec5a29e9fc5a40d2e3a1607565db4756655f2afc",
          "sha1": "55182054b09b4b11ccdcee2cfa61e19d454c197b",
          "md5": "1e1e7707bfde3b4e57bd669e32f2808e"
        }
      ]
    }
  ]
}
