{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "mpjhtqfpbnakfoiuuego6oyugu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.0.1.jar",
          "url": "kodein-internal-gradle-plugin-5.0.1.jar",
          "size": 249292,
          "sha512": "74bfa5df10477db2d4446ae6142f0c374f65021770bad1717c786f40a2c08086f11022afde0c0cac4cf7cd67bc90c67cced8f8546b3a551657ca08bbabf19ac0",
          "sha256": "90a41d49bb95815dd8102ba76b9ca19b47081e6340671b19ef17cb2138147c72",
          "sha1": "b60fe414906fbdf8a76f324d159dedef246234e7",
          "md5": "82a11c45402cb7c9aa7de129eab5f80a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.0.1.jar",
          "url": "kodein-internal-gradle-plugin-5.0.1.jar",
          "size": 249292,
          "sha512": "74bfa5df10477db2d4446ae6142f0c374f65021770bad1717c786f40a2c08086f11022afde0c0cac4cf7cd67bc90c67cced8f8546b3a551657ca08bbabf19ac0",
          "sha256": "90a41d49bb95815dd8102ba76b9ca19b47081e6340671b19ef17cb2138147c72",
          "sha1": "b60fe414906fbdf8a76f324d159dedef246234e7",
          "md5": "82a11c45402cb7c9aa7de129eab5f80a"
        }
      ]
    }
  ]
}
