{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "8.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.5.1.jar",
          "url": "kodein-internal-gradle-settings-8.5.1.jar",
          "size": 29892,
          "sha512": "f43901909dea9dab011b78aff2d37b926154a0e93ba427086f121200c998947eaa02eb28585fefe6fd1ceea73847d2f0dd72a807169c73853edb07d5f6ee15b3",
          "sha256": "9f64359304e579b6bf19c823a7c444d48532a67f1083c17019c5dd3c1c1461dd",
          "sha1": "dcc5a49f4440efc1a663d2021866cf15c69fda84",
          "md5": "906e467034d4e87f63c87c6d1d225da3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.5.1.jar",
          "url": "kodein-internal-gradle-settings-8.5.1.jar",
          "size": 29892,
          "sha512": "f43901909dea9dab011b78aff2d37b926154a0e93ba427086f121200c998947eaa02eb28585fefe6fd1ceea73847d2f0dd72a807169c73853edb07d5f6ee15b3",
          "sha256": "9f64359304e579b6bf19c823a7c444d48532a67f1083c17019c5dd3c1c1461dd",
          "sha1": "dcc5a49f4440efc1a663d2021866cf15c69fda84",
          "md5": "906e467034d4e87f63c87c6d1d225da3"
        }
      ]
    }
  ]
}
