[versions]
# https://docs.gradle.org/current/userguide/compatibility.html#kotlin
kotlin = "1.9.10"
gradle-publishPlugin = "1.1.0"
gradle-enterprisePlugin = "3.15.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-enterprise = { id = "com.gradle.enterprise", version.ref = "gradle-enterprisePlugin" }

[libraries]
gradle-publishPlugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradle-publishPlugin" }
gradle-enterprisePlugin = { module = "com.gradle.enterprise:com.gradle.enterprise.gradle.plugin", version.ref = "gradle-enterprisePlugin" }
