{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "5.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "2urxlgu7erfdzdoaaimoy2z4bq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.5.0.jar",
          "url": "kodein-internal-gradle-plugin-5.5.0.jar",
          "size": 250803,
          "sha512": "0c9bfc93144d36dea589bc512b5b413e2aba9e2de2283b87206cacd0ac08c29c7b46bcb0f9a660f5db868be28b22f8e477d6783f384f7d64ef239cff20e2f2fd",
          "sha256": "35066c1df095666c58fd5246ab1f3c2b07ffe3c3856edf8689184100c8827fb9",
          "sha1": "0c38de62ed9f249071d8add9654b23f42315c2ba",
          "md5": "118d2b5d5c97b70017585c035698b228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.5.0.jar",
          "url": "kodein-internal-gradle-plugin-5.5.0.jar",
          "size": 250803,
          "sha512": "0c9bfc93144d36dea589bc512b5b413e2aba9e2de2283b87206cacd0ac08c29c7b46bcb0f9a660f5db868be28b22f8e477d6783f384f7d64ef239cff20e2f2fd",
          "sha256": "35066c1df095666c58fd5246ab1f3c2b07ffe3c3856edf8689184100c8827fb9",
          "sha1": "0c38de62ed9f249071d8add9654b23f42315c2ba",
          "md5": "118d2b5d5c97b70017585c035698b228"
        }
      ]
    }
  ]
}
