{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "8.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.8.0.jar",
          "url": "kodein-internal-gradle-settings-8.8.0.jar",
          "size": 29866,
          "sha512": "015cd605d3bddfae5cc4c2046dbfe5a2958e0cfc072779dbad3c2a7dd8be61f0a3876f369c41c4e550f169e7da9a59d26c0a385ef99ec3f24129b983c98c5536",
          "sha256": "a97e9d2e097f3669bd339b8a5244c36e63c87bac0ebeac8f6533e7b62cf37438",
          "sha1": "99116704dec2000315e5c523a11d9ed016af8df4",
          "md5": "90864c3dcb36ae94be914ff36ccd06b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.8.0.jar",
          "url": "kodein-internal-gradle-settings-8.8.0.jar",
          "size": 29866,
          "sha512": "015cd605d3bddfae5cc4c2046dbfe5a2958e0cfc072779dbad3c2a7dd8be61f0a3876f369c41c4e550f169e7da9a59d26c0a385ef99ec3f24129b983c98c5536",
          "sha256": "a97e9d2e097f3669bd339b8a5244c36e63c87bac0ebeac8f6533e7b62cf37438",
          "sha1": "99116704dec2000315e5c523a11d9ed016af8df4",
          "md5": "90864c3dcb36ae94be914ff36ccd06b3"
        }
      ]
    }
  ]
}
