{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tcspym4hh5epxmzdrzwk26j5zu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0.jar",
          "size": 245110,
          "sha512": "5bc8368a0070701d9ca4943c199f1c0ad73d126d62c88b7be8e70e3351ec6206d0b5305d2fb866243d695d381644328625cc4ad241dd7fce722960cf41c6b6c6",
          "sha256": "b3063e286ac4e45aed917d5648331cb770f7ec0e3d77dab52b0a6858c6671ed3",
          "sha1": "1abb232ea5aee111c1ccb9c224062a7b1aa61fc8",
          "md5": "c70a63b5dd6b538f8b71f430286a8403"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0.jar",
          "size": 245110,
          "sha512": "5bc8368a0070701d9ca4943c199f1c0ad73d126d62c88b7be8e70e3351ec6206d0b5305d2fb866243d695d381644328625cc4ad241dd7fce722960cf41c6b6c6",
          "sha256": "b3063e286ac4e45aed917d5648331cb770f7ec0e3d77dab52b0a6858c6671ed3",
          "sha1": "1abb232ea5aee111c1ccb9c224062a7b1aa61fc8",
          "md5": "c70a63b5dd6b538f8b71f430286a8403"
        }
      ]
    }
  ]
}
