{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "izzhweihtnanni3haviszdo7z4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0.jar",
          "size": 245110,
          "sha512": "ab4cdc5c58c4ff1495e6d6b6fd078f48e6599975e7846e62427f34a6484b779d092605b1c1c9ae196dc83d08244e5f61443f80e4af3107addc5126ccf5e3b07a",
          "sha256": "50b74780d63188011734c34d5ccd725e3d3a92bf3f797e7c39ed9d220c4ede23",
          "sha1": "33334351d35fa61b25846036267540ee44ec5a35",
          "md5": "21b48f1366c09931537f6748a485fdc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0.jar",
          "size": 245110,
          "sha512": "ab4cdc5c58c4ff1495e6d6b6fd078f48e6599975e7846e62427f34a6484b779d092605b1c1c9ae196dc83d08244e5f61443f80e4af3107addc5126ccf5e3b07a",
          "sha256": "50b74780d63188011734c34d5ccd725e3d3a92bf3f797e7c39ed9d220c4ede23",
          "sha1": "33334351d35fa61b25846036267540ee44ec5a35",
          "md5": "21b48f1366c09931537f6748a485fdc1"
        }
      ]
    }
  ]
}
