{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ayimeqlslnajnkcs2l5mgvkplm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0.jar",
          "size": 245110,
          "sha512": "8748ff20de435844f3e6351bd2042567132ccc58133e22267c54a7680c228816501b7cac3544a6c2d8ab5cba2bda3dec54ccea3bf17f25de6954bd8c6a87a8ee",
          "sha256": "03568dc851f47aa4892686b4e1ce9f18e4d20341ddfa5c0f38df1e4a604ecf4b",
          "sha1": "cf7cb352ea943a700f41decaef97261ed3f32436",
          "md5": "c271970c5f576421f580971b2c2e3319"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.0.0.jar",
          "url": "kodein-internal-gradle-plugin-6.0.0.jar",
          "size": 245110,
          "sha512": "8748ff20de435844f3e6351bd2042567132ccc58133e22267c54a7680c228816501b7cac3544a6c2d8ab5cba2bda3dec54ccea3bf17f25de6954bd8c6a87a8ee",
          "sha256": "03568dc851f47aa4892686b4e1ce9f18e4d20341ddfa5c0f38df1e4a604ecf4b",
          "sha1": "cf7cb352ea943a700f41decaef97261ed3f32436",
          "md5": "c271970c5f576421f580971b2c2e3319"
        }
      ]
    }
  ]
}
