{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.1.0.jar",
          "url": "kodein-internal-gradle-plugin-8.1.0.jar",
          "size": 432477,
          "sha512": "d26c3cb6c05e62ba05de8893c8fce832a91a52ccb7d750b554d99c899bc335b6c6858abaf0f0472e9bb0ee9331d3e5d4966bbf73d200dbbbe5e8d271fe3c967c",
          "sha256": "c7e5d33e8c0459324b0a03bbe017dcc7d7a5bf2c6a63c8300c4462ac2c0642c7",
          "sha1": "b784b3bd019e2628fcc74e4b4cbe61418ad1f2d1",
          "md5": "82de21de439f2e73f60119b69b7ccd1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.1.0.jar",
          "url": "kodein-internal-gradle-plugin-8.1.0.jar",
          "size": 432477,
          "sha512": "d26c3cb6c05e62ba05de8893c8fce832a91a52ccb7d750b554d99c899bc335b6c6858abaf0f0472e9bb0ee9331d3e5d4966bbf73d200dbbbe5e8d271fe3c967c",
          "sha256": "c7e5d33e8c0459324b0a03bbe017dcc7d7a5bf2c6a63c8300c4462ac2c0642c7",
          "sha1": "b784b3bd019e2628fcc74e4b4cbe61418ad1f2d1",
          "md5": "82de21de439f2e73f60119b69b7ccd1d"
        }
      ]
    }
  ]
}
