{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.7.1.jar",
          "url": "kodein-internal-gradle-plugin-6.7.1.jar",
          "size": 256855,
          "sha512": "3cb796c6cfdc9c81cea95022ec02419c65a16a98490adcd887242042b314d09b2dbafd26bbd80db66432200379e0ee4fde3ab74467ae7121f04fdda94a3b9f9b",
          "sha256": "6d6bcf67b284fe22a1d3902eefcaf55a2415f3414ef02c067dcb837f868635db",
          "sha1": "d5cd520619ed8588248e81da71a789dac9185f83",
          "md5": "bd2e19902a34d5957a6cb9216503b0dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.7.1.jar",
          "url": "kodein-internal-gradle-plugin-6.7.1.jar",
          "size": 256855,
          "sha512": "3cb796c6cfdc9c81cea95022ec02419c65a16a98490adcd887242042b314d09b2dbafd26bbd80db66432200379e0ee4fde3ab74467ae7121f04fdda94a3b9f9b",
          "sha256": "6d6bcf67b284fe22a1d3902eefcaf55a2415f3414ef02c067dcb837f868635db",
          "sha1": "d5cd520619ed8588248e81da71a789dac9185f83",
          "md5": "bd2e19902a34d5957a6cb9216503b0dc"
        }
      ]
    }
  ]
}
