{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "5.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "3vr53b37zjb53g5bu5dxk3jvhy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.10.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.2.2.jar",
          "url": "kodein-internal-gradle-plugin-5.2.2.jar",
          "size": 253258,
          "sha512": "22c6ff203a533dc4f729a6d205862a4ecb14a4b791924f4f8af6779b3d2f7f918f209ccccaf382547f3a3ef569fbe816cd4c5c7e681120cc7f247b3a7fa80ab6",
          "sha256": "c01bd97b727e904555aa7cdd66c86e550c37f0b51fb0592b257e6292438c108e",
          "sha1": "11134af9596dd0bedf9883b7a4c8ec38eea45ad0",
          "md5": "3937cdcb6bb52f52178ca4b713793c32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.10.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.2.2.jar",
          "url": "kodein-internal-gradle-plugin-5.2.2.jar",
          "size": 253258,
          "sha512": "22c6ff203a533dc4f729a6d205862a4ecb14a4b791924f4f8af6779b3d2f7f918f209ccccaf382547f3a3ef569fbe816cd4c5c7e681120cc7f247b3a7fa80ab6",
          "sha256": "c01bd97b727e904555aa7cdd66c86e550c37f0b51fb0592b257e6292438c108e",
          "sha1": "11134af9596dd0bedf9883b7a4c8ec38eea45ad0",
          "md5": "3937cdcb6bb52f52178ca4b713793c32"
        }
      ]
    }
  ]
}
