{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "8.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.5.0.jar",
          "url": "kodein-internal-gradle-settings-8.5.0.jar",
          "size": 29894,
          "sha512": "d54b6a2a18518cfe136a675253fbe0981f5c3d54bd2db85d2063ebc68b7ad612c606c943ad515f65a8cf566ca7e0a75b0453683cf090e669158e3956d6f3a7de",
          "sha256": "72acb8f10864e15279469dbff9724ec8ab7300048d29c2d54a1a5481b046a5bb",
          "sha1": "9bd362e5671c8524f36cb0f254eb9db6f41485a8",
          "md5": "9711324bb5263b89484ab334661a170e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.5.0.jar",
          "url": "kodein-internal-gradle-settings-8.5.0.jar",
          "size": 29894,
          "sha512": "d54b6a2a18518cfe136a675253fbe0981f5c3d54bd2db85d2063ebc68b7ad612c606c943ad515f65a8cf566ca7e0a75b0453683cf090e669158e3956d6f3a7de",
          "sha256": "72acb8f10864e15279469dbff9724ec8ab7300048d29c2d54a1a5481b046a5bb",
          "sha1": "9bd362e5671c8524f36cb0f254eb9db6f41485a8",
          "md5": "9711324bb5263b89484ab334661a170e"
        }
      ]
    }
  ]
}
