{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.9.0.jar",
          "url": "kodein-internal-gradle-plugin-6.9.0.jar",
          "size": 262069,
          "sha512": "caa6bcb670bb71e715dd60263cef958a068e122859227466b5efb77d1ca3d56160e01bedfecbb310fda1b4effa7dc0ca63733c10e21ce01f9996cd242c937f14",
          "sha256": "29c95f8efb5a8362f2abe0015b5427778410f64e31270102a21a5629c0e88087",
          "sha1": "8d5786c9c9ec5da19d6ac66802f0000455eda9fe",
          "md5": "b68f9369dd3c433334c52c4aaee37ff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.9.0.jar",
          "url": "kodein-internal-gradle-plugin-6.9.0.jar",
          "size": 262069,
          "sha512": "caa6bcb670bb71e715dd60263cef958a068e122859227466b5efb77d1ca3d56160e01bedfecbb310fda1b4effa7dc0ca63733c10e21ce01f9996cd242c937f14",
          "sha256": "29c95f8efb5a8362f2abe0015b5427778410f64e31270102a21a5629c0e88087",
          "sha1": "8d5786c9c9ec5da19d6ac66802f0000455eda9fe",
          "md5": "b68f9369dd3c433334c52c4aaee37ff8"
        }
      ]
    }
  ]
}
