{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "c7k7qfkgp5eetbk5oaqmq57ke4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.1.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-6.1.0-SNAPSHOT.jar",
          "size": 245110,
          "sha512": "ea5b1618f4921ab521d38e7feb01599a10e03ef81519fe2ca1c2b51ee5728c26d32fdef86289b5b79a4a3615ce515334309f0c39e6303d7c7bd7e170a8a2931a",
          "sha256": "547c153f8d8c4a855bdd40d886433eb6d4acdcb8b8be75daf283edeaa992c8fa",
          "sha1": "f5ee5c50501efacd155e4ae018cc2ae6e9efea30",
          "md5": "2e80380b67fdaf6b77bb04d066b28435"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.1.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-6.1.0-SNAPSHOT.jar",
          "size": 245110,
          "sha512": "ea5b1618f4921ab521d38e7feb01599a10e03ef81519fe2ca1c2b51ee5728c26d32fdef86289b5b79a4a3615ce515334309f0c39e6303d7c7bd7e170a8a2931a",
          "sha256": "547c153f8d8c4a855bdd40d886433eb6d4acdcb8b8be75daf283edeaa992c8fa",
          "sha1": "f5ee5c50501efacd155e4ae018cc2ae6e9efea30",
          "md5": "2e80380b67fdaf6b77bb04d066b28435"
        }
      ]
    }
  ]
}
