{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.gradleup.nmcp.aggregation",
          "module": "com.gradleup.nmcp.aggregation.gradle.plugin",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "3.19"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.15.0.jar",
          "url": "kodein-internal-gradle-plugin-8.15.0.jar",
          "size": 273116,
          "sha512": "a3b30825cec6f40a6a652011c05681edad6f39e063c57b2c9a304ca2078cc23cf99e366df1073e70c95d2d2b5198828aab714fb11044ea78f424f7d4a91f2234",
          "sha256": "01bda6abaa25274e0cb98dccc98836ec0bba7aaa36e08e430da879dbafbea7f7",
          "sha1": "e22ab3e12d6e87c047bc9a2f6b3e7fff389d56d6",
          "md5": "fde2a25e6297fb4070590e1c65cd360a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.gradleup.nmcp.aggregation",
          "module": "com.gradleup.nmcp.aggregation.gradle.plugin",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "3.19"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.15.0.jar",
          "url": "kodein-internal-gradle-plugin-8.15.0.jar",
          "size": 273116,
          "sha512": "a3b30825cec6f40a6a652011c05681edad6f39e063c57b2c9a304ca2078cc23cf99e366df1073e70c95d2d2b5198828aab714fb11044ea78f424f7d4a91f2234",
          "sha256": "01bda6abaa25274e0cb98dccc98836ec0bba7aaa36e08e430da879dbafbea7f7",
          "sha1": "e22ab3e12d6e87c047bc9a2f6b3e7fff389d56d6",
          "md5": "fde2a25e6297fb4070590e1c65cd360a"
        }
      ]
    }
  ]
}
