{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "5.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "77cn6wimszfvvidpgylfz2uifa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.0.2.jar",
          "url": "kodein-internal-gradle-plugin-5.0.2.jar",
          "size": 249560,
          "sha512": "3f4d7501a9ad4278d00fff2953f4aee648b139bdbe72d8b526ad7c102db95a5eb09c4e744d73e94e37632ca690f9c395d58ed79ea1d861597392057f121f2c9c",
          "sha256": "b4efe1150a4742f59c266e4fada0a18c75349e5f4f280deadbb7a97a814bd509",
          "sha1": "f12795f7f93d1e5706c46323f0d3992072655119",
          "md5": "8efd5269e338ababe2cdbf76ae7891cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.0.2.jar",
          "url": "kodein-internal-gradle-plugin-5.0.2.jar",
          "size": 249560,
          "sha512": "3f4d7501a9ad4278d00fff2953f4aee648b139bdbe72d8b526ad7c102db95a5eb09c4e744d73e94e37632ca690f9c395d58ed79ea1d861597392057f121f2c9c",
          "sha256": "b4efe1150a4742f59c266e4fada0a18c75349e5f4f280deadbb7a97a814bd509",
          "sha1": "f12795f7f93d1e5706c46323f0d3992072655119",
          "md5": "8efd5269e338ababe2cdbf76ae7891cf"
        }
      ]
    }
  ]
}
