{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.9.0.jar",
          "url": "kodein-internal-gradle-settings-6.9.0.jar",
          "size": 16417,
          "sha512": "035a2413e6506eb2c79bd53dc636797d23aadc498ad9d3788b8edc0e3c5a5765039590a12480dfea4ca6b0f6032fbbffc0c5b1c63e857bc0ef10049932034492",
          "sha256": "7a12e348766789d63584027880e7ede9753b885be0b21f18c19e4915b53b5955",
          "sha1": "55b36e60985287bae777a014a4f6932f53fa424d",
          "md5": "c8688ff6144083dd3742c660e162a6d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.9.0.jar",
          "url": "kodein-internal-gradle-settings-6.9.0.jar",
          "size": 16417,
          "sha512": "035a2413e6506eb2c79bd53dc636797d23aadc498ad9d3788b8edc0e3c5a5765039590a12480dfea4ca6b0f6032fbbffc0c5b1c63e857bc0ef10049932034492",
          "sha256": "7a12e348766789d63584027880e7ede9753b885be0b21f18c19e4915b53b5955",
          "sha1": "55b36e60985287bae777a014a4f6932f53fa424d",
          "md5": "c8688ff6144083dd3742c660e162a6d9"
        }
      ]
    }
  ]
}
