{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "c7k7qfkgp5eetbk5oaqmq57ke4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.1.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.1.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "1b7fd4ac3dd6b3d7c0f4893e34c0d4f88177a950d40bd8612db9a00c757a48e2c2dde55536cf324d3d55d871e3010cd06b7a6e00993340429c77ee343ae2060c",
          "sha256": "c42e35c2d61fe8c49e82d321503dc6d4dbf28951b3df14dc68c9f94511f46099",
          "sha1": "01df9ff0d57eb3ab8597b56dac76e2363e56e647",
          "md5": "8b6cbaaf5006b99105d7aa2e132f583d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.1.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.1.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "1b7fd4ac3dd6b3d7c0f4893e34c0d4f88177a950d40bd8612db9a00c757a48e2c2dde55536cf324d3d55d871e3010cd06b7a6e00993340429c77ee343ae2060c",
          "sha256": "c42e35c2d61fe8c49e82d321503dc6d4dbf28951b3df14dc68c9f94511f46099",
          "sha1": "01df9ff0d57eb3ab8597b56dac76e2363e56e647",
          "md5": "8b6cbaaf5006b99105d7aa2e132f583d"
        }
      ]
    }
  ]
}
