{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "unaabr4ctrghliajts2ackrcri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-3.4.3.jar",
          "url": "kodein-internal-gradle-versions-3.4.3.jar",
          "size": 3088,
          "sha512": "f659e6527b8a7336bcd63432e6aa327be14b6a691b8201dbf1c0a26373518c3314895047f7bdeaf38612558e6f37107dc982a8436b74907dc0dfea5f871e8b4b",
          "sha256": "382a15fe441ce212ef76feb72393c695c54d21c7699e73af78f56a063f3f63ea",
          "sha1": "6bf3a6495fbdd8dea0dc9399afa1268565cd6673",
          "md5": "30c36055ecdad4982775895a472e9523"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-3.4.3.jar",
          "url": "kodein-internal-gradle-versions-3.4.3.jar",
          "size": 3088,
          "sha512": "f659e6527b8a7336bcd63432e6aa327be14b6a691b8201dbf1c0a26373518c3314895047f7bdeaf38612558e6f37107dc982a8436b74907dc0dfea5f871e8b4b",
          "sha256": "382a15fe441ce212ef76feb72393c695c54d21c7699e73af78f56a063f3f63ea",
          "sha1": "6bf3a6495fbdd8dea0dc9399afa1268565cd6673",
          "md5": "30c36055ecdad4982775895a472e9523"
        }
      ]
    }
  ]
}
