{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "kggbeakbarghbhjo4uac4uqq5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "f1454ac518e2f4b4ff12b6b41454b1f328b17afc1505a754a8eb29ab7699e666c9fbc63c461be3c789c96aa0ee96dbef4c19f428359b64c3774fe0594d745d33",
          "sha256": "4c549fac3263467484ee03584aa82ab50b57d679d6143485c4e6d64cddfffc26",
          "sha1": "88b90754d09a412a2d3f131583f8ad5dd342b66e",
          "md5": "9ba95c8e3dac1564fcdcc855a4fb4539"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "f1454ac518e2f4b4ff12b6b41454b1f328b17afc1505a754a8eb29ab7699e666c9fbc63c461be3c789c96aa0ee96dbef4c19f428359b64c3774fe0594d745d33",
          "sha256": "4c549fac3263467484ee03584aa82ab50b57d679d6143485c4e6d64cddfffc26",
          "sha1": "88b90754d09a412a2d3f131583f8ad5dd342b66e",
          "md5": "9ba95c8e3dac1564fcdcc855a4fb4539"
        }
      ]
    }
  ]
}
