{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "du3w4txvu5cxfpowbmycmxof7y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "c063d72e6d11d64f12c91516dbfa1d733522a76981f07669fcfea0e085db7df58b7f44c6575f9603ce61d7c37a1636429f42d02ca722effc49ca76f84c9055c4",
          "sha256": "73f7d29df9b989814473571833b8190a517123e67ce9fb4143b58ca7731ae68d",
          "sha1": "bf20a2079348ff7ee872cd78aeab2e5a89306f3b",
          "md5": "f05d2b43c90600aa0c1dc2c2551a1e61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "c063d72e6d11d64f12c91516dbfa1d733522a76981f07669fcfea0e085db7df58b7f44c6575f9603ce61d7c37a1636429f42d02ca722effc49ca76f84c9055c4",
          "sha256": "73f7d29df9b989814473571833b8190a517123e67ce9fb4143b58ca7731ae68d",
          "sha1": "bf20a2079348ff7ee872cd78aeab2e5a89306f3b",
          "md5": "f05d2b43c90600aa0c1dc2c2551a1e61"
        }
      ]
    }
  ]
}
