{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "4iktlfqxoncudgar4wqgadjkwa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "9c070e7b26a72c08f2d78b94a2466eb73046382497f8d75f16e96e26100e1d92072a6d8404e9004fc9c8314305de213e4dbfbc3b29e0cd4f0fa2893bcfa0480f",
          "sha256": "0ab351564505d04f768c80b792499f95a7e04886d507d05a75cbc6efa05058cf",
          "sha1": "59c7a01923d7de7e0cda80b10653f2ad6f0a6560",
          "md5": "83d587673e2b83e8e28071fb5fb052f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.0.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "9c070e7b26a72c08f2d78b94a2466eb73046382497f8d75f16e96e26100e1d92072a6d8404e9004fc9c8314305de213e4dbfbc3b29e0cd4f0fa2893bcfa0480f",
          "sha256": "0ab351564505d04f768c80b792499f95a7e04886d507d05a75cbc6efa05058cf",
          "sha1": "59c7a01923d7de7e0cda80b10653f2ad6f0a6560",
          "md5": "83d587673e2b83e8e28071fb5fb052f5"
        }
      ]
    }
  ]
}
