{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.9.1.jar",
          "url": "kodein-internal-gradle-plugin-6.9.1.jar",
          "size": 262070,
          "sha512": "1f5d1a9479702594999f9f5f58a9f6a454d2914925145d6fb1b51cbebdc1d9a1136cd1ce267afaceddaac5ed0e13a382a39ff812bfed91bd51c3a0b7bd648b4d",
          "sha256": "16c5bae944ad4c56ff10281f467f120d1186b7dd6dc7b2bbfeee24ea63bd1bb8",
          "sha1": "265655b9299de28e4fafa7866843ca785fe51f77",
          "md5": "76274b9a2af5a8645e589010b1072f91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.9.1.jar",
          "url": "kodein-internal-gradle-plugin-6.9.1.jar",
          "size": 262070,
          "sha512": "1f5d1a9479702594999f9f5f58a9f6a454d2914925145d6fb1b51cbebdc1d9a1136cd1ce267afaceddaac5ed0e13a382a39ff812bfed91bd51c3a0b7bd648b4d",
          "sha256": "16c5bae944ad4c56ff10281f467f120d1186b7dd6dc7b2bbfeee24ea63bd1bb8",
          "sha1": "265655b9299de28e4fafa7866843ca785fe51f77",
          "md5": "76274b9a2af5a8645e589010b1072f91"
        }
      ]
    }
  ]
}
