{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qr65gxulofftvk6gbesusz77j4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.5.0.jar",
          "url": "kodein-internal-gradle-plugin-6.5.0.jar",
          "size": 259880,
          "sha512": "ecf03795a9e978b5e6a683e576f3ffb89dce0f17c7bfde5954440d618a5272041ee07f666764d7d44d03617b95ea79122c2af064b975ad7a7bc4b6e8cf11df03",
          "sha256": "e1c9defce1a797d89af48ccdb6e22b61c47a4820c7441ade949f56d34b3ddeda",
          "sha1": "0cb315cc573eecda52d678311693c07ed3bcfece",
          "md5": "4c21f5c3f184f4a96d8dedb1c0124195"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.5.0.jar",
          "url": "kodein-internal-gradle-plugin-6.5.0.jar",
          "size": 259880,
          "sha512": "ecf03795a9e978b5e6a683e576f3ffb89dce0f17c7bfde5954440d618a5272041ee07f666764d7d44d03617b95ea79122c2af064b975ad7a7bc4b6e8cf11df03",
          "sha256": "e1c9defce1a797d89af48ccdb6e22b61c47a4820c7441ade949f56d34b3ddeda",
          "sha1": "0cb315cc573eecda52d678311693c07ed3bcfece",
          "md5": "4c21f5c3f184f4a96d8dedb1c0124195"
        }
      ]
    }
  ]
}
