{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "5.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "enfbpwdgrngxvnw6jviw45zlyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.6.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-5.6.0-SNAPSHOT.jar",
          "size": 250804,
          "sha512": "9050fb8a133dc4cd6ada6e2450d7fe12806f66f828e0906d077c50d222618bb9fd811c60e9435c72f13afe82a360da6aebe938fc265aeaa6b9d35cf5fbb4d57f",
          "sha256": "5e8919a4a055f817ca1e946a7f5050771cf6b091d414172ddec7de2b9cfa5f92",
          "sha1": "4e51c9957026d9e068faa451dd24cf2a50e8b5ed",
          "md5": "cfe4fed0e28a320277f65fc582a38fae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.6.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-5.6.0-SNAPSHOT.jar",
          "size": 250804,
          "sha512": "9050fb8a133dc4cd6ada6e2450d7fe12806f66f828e0906d077c50d222618bb9fd811c60e9435c72f13afe82a360da6aebe938fc265aeaa6b9d35cf5fbb4d57f",
          "sha256": "5e8919a4a055f817ca1e946a7f5050771cf6b091d414172ddec7de2b9cfa5f92",
          "sha1": "4e51c9957026d9e068faa451dd24cf2a50e8b5ed",
          "md5": "cfe4fed0e28a320277f65fc582a38fae"
        }
      ]
    }
  ]
}
