{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "8.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.7.1.jar",
          "url": "kodein-internal-gradle-settings-8.7.1.jar",
          "size": 29865,
          "sha512": "571c0201e2fdff31b9036484f939715e127f3171eeae6e72f89fe089cb69cbe0ad642a629c5cefbdda83095017b95f976b4e34b77a2a5fa2cd78df2113960947",
          "sha256": "c5ed39fd9bd03fabfd89cfdae0dfaeac04267be71322d288dcb8cfe1e3ad78d0",
          "sha1": "2c1a6dba954b5ad53e041e9feb834a3b1f0b861c",
          "md5": "9a7a96abeac9fac23a50af8916859318"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.7.1.jar",
          "url": "kodein-internal-gradle-settings-8.7.1.jar",
          "size": 29865,
          "sha512": "571c0201e2fdff31b9036484f939715e127f3171eeae6e72f89fe089cb69cbe0ad642a629c5cefbdda83095017b95f976b4e34b77a2a5fa2cd78df2113960947",
          "sha256": "c5ed39fd9bd03fabfd89cfdae0dfaeac04267be71322d288dcb8cfe1e3ad78d0",
          "sha1": "2c1a6dba954b5ad53e041e9feb834a3b1f0b861c",
          "md5": "9a7a96abeac9fac23a50af8916859318"
        }
      ]
    }
  ]
}
