{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.gradleup.nmcp.aggregation",
          "module": "com.gradleup.nmcp.aggregation.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.19.0.jar",
          "url": "kodein-internal-gradle-plugin-8.19.0.jar",
          "size": 263626,
          "sha512": "8c40b04a5aff11f0b1b2f33680dc763559eb6cf9fc8f57a73f5598953ac547d3e47b8abec964874b00e13cf1ed1395492fcb61fa4633b1ef157b701e4699eb25",
          "sha256": "88c3472af1d781e27c6c88f8d2114db242ec6c745d17de7602ad3467c4652776",
          "sha1": "96267822d22a452db074d457712f672d955b7454",
          "md5": "32cea609a95c5583a2929ac32bb7cb53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.gradleup.nmcp.aggregation",
          "module": "com.gradleup.nmcp.aggregation.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.19.0.jar",
          "url": "kodein-internal-gradle-plugin-8.19.0.jar",
          "size": 263626,
          "sha512": "8c40b04a5aff11f0b1b2f33680dc763559eb6cf9fc8f57a73f5598953ac547d3e47b8abec964874b00e13cf1ed1395492fcb61fa4633b1ef157b701e4699eb25",
          "sha256": "88c3472af1d781e27c6c88f8d2114db242ec6c745d17de7602ad3467c4652776",
          "sha1": "96267822d22a452db074d457712f672d955b7454",
          "md5": "32cea609a95c5583a2929ac32bb7cb53"
        }
      ]
    }
  ]
}
