{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "8.7.0-kotlin-2.0.0-RC3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.jar",
          "size": 29922,
          "sha512": "5593df28471385db982777d01c20e902e4212f523ef3db38aa050e936cfc7caa6649a8bc96f9ccc8e5b6b4203d9a4c47f7ffd398652fa34edbe116f0860567d0",
          "sha256": "b3ba1448c9963af684f8da6e1bbdc6e2e874c080aaa045e877ffe457bb7bdb99",
          "sha1": "c5271fe289f48cc99cf91bc62797f5f5e8d7f909",
          "md5": "5be8216f9fd38526a8c503d6823bb735"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.jar",
          "size": 29922,
          "sha512": "5593df28471385db982777d01c20e902e4212f523ef3db38aa050e936cfc7caa6649a8bc96f9ccc8e5b6b4203d9a4c47f7ffd398652fa34edbe116f0860567d0",
          "sha256": "b3ba1448c9963af684f8da6e1bbdc6e2e874c080aaa045e877ffe457bb7bdb99",
          "sha1": "c5271fe289f48cc99cf91bc62797f5f5e8d7f909",
          "md5": "5be8216f9fd38526a8c503d6823bb735"
        }
      ]
    }
  ]
}
