{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.18.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.18.3-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.18.3-SNAPSHOT.jar",
          "size": 3149,
          "sha512": "42df8c015edb1c79f2f7a972f2e5a73b7c74861acffbe4c4a5b6b84ce606fd0b4995962599a002730f08213ee4903802f1e2e8f1ec235e63b0f49670413d31fc",
          "sha256": "f0d3542b57f6813da932ff7f91d62fd88db9115b109c5eb36ff1b500e376d244",
          "sha1": "c48bbf6d459c27478ea4691ab113970c66727c1c",
          "md5": "59b30e75af1ab95758c3d6fe838dac5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.18.3-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.18.3-SNAPSHOT.jar",
          "size": 3149,
          "sha512": "42df8c015edb1c79f2f7a972f2e5a73b7c74861acffbe4c4a5b6b84ce606fd0b4995962599a002730f08213ee4903802f1e2e8f1ec235e63b0f49670413d31fc",
          "sha256": "f0d3542b57f6813da932ff7f91d62fd88db9115b109c5eb36ff1b500e376d244",
          "sha1": "c48bbf6d459c27478ea4691ab113970c66727c1c",
          "md5": "59b30e75af1ab95758c3d6fe838dac5a"
        }
      ]
    }
  ]
}
