{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.7.0-kotlin-2.0.0-RC2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.7.0-kotlin-2.0.0-RC2-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-8.7.0-kotlin-2.0.0-RC2-SNAPSHOT.jar",
          "size": 438523,
          "sha512": "2a259834e33f59d68db56870ffc18309c768ed153a7168b58fa77414df800af8a269b34c78f067a6b5b78f9346e137735d9eebe4e523d002986bdc9c27d8685d",
          "sha256": "a83657e74f94ca4f6f1b108f19140ce03730d561aed242e5402e9de2b7a72d18",
          "sha1": "588c2ce2c79135641ef8795164d548d44bf1b8ce",
          "md5": "710d2e6f8916b56ebe6a87d177500e87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.7.0-kotlin-2.0.0-RC2-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-8.7.0-kotlin-2.0.0-RC2-SNAPSHOT.jar",
          "size": 438523,
          "sha512": "2a259834e33f59d68db56870ffc18309c768ed153a7168b58fa77414df800af8a269b34c78f067a6b5b78f9346e137735d9eebe4e523d002986bdc9c27d8685d",
          "sha256": "a83657e74f94ca4f6f1b108f19140ce03730d561aed242e5402e9de2b7a72d18",
          "sha1": "588c2ce2c79135641ef8795164d548d44bf1b8ce",
          "md5": "710d2e6f8916b56ebe6a87d177500e87"
        }
      ]
    }
  ]
}
