{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.23.0.jar",
          "url": "kodein-internal-gradle-plugin-6.23.0.jar",
          "size": 274320,
          "sha512": "b7cb4c8ebfdfe7d19abdea22439f9f697ccb3c2a40bbe15ce4027d32600237ed2caf7a69261afff6535cd39dffcf45004411d951ec7c7b5cde31a1dd964a204f",
          "sha256": "6b45d494566a5d6e3bb5506a372870600e6b2fc7520189eff387bf2cbc8840f3",
          "sha1": "6e8c58b528ecd099b77ccdc47be5703e9a8c7d67",
          "md5": "42ba0c20061b52426364033d5d35d53d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.23.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.23.0.jar",
          "url": "kodein-internal-gradle-plugin-6.23.0.jar",
          "size": 274320,
          "sha512": "b7cb4c8ebfdfe7d19abdea22439f9f697ccb3c2a40bbe15ce4027d32600237ed2caf7a69261afff6535cd39dffcf45004411d951ec7c7b5cde31a1dd964a204f",
          "sha256": "6b45d494566a5d6e3bb5506a372870600e6b2fc7520189eff387bf2cbc8840f3",
          "sha1": "6e8c58b528ecd099b77ccdc47be5703e9a8c7d67",
          "md5": "42ba0c20061b52426364033d5d35d53d"
        }
      ]
    }
  ]
}
