{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "5.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "enfbpwdgrngxvnw6jviw45zlyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-5.6.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-5.6.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "312af8791c61800b2ce5b992b5e7db1c5ea3c9e864cd8d8aab19f397aaeee18c22ba38c5de736bf1361a6efc4574e2daa63c80a20471a30a4e97111b32d39cf1",
          "sha256": "c5c11929f2e5453c3fd93474e8934f9eca740beaa78a0a8152afe634a1aeec06",
          "sha1": "3fd96e78b80bf98b1b4b224fcabea47f435aac3a",
          "md5": "93a207ce0646fe1297ae396202327015"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-5.6.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-5.6.0-SNAPSHOT.jar",
          "size": 3147,
          "sha512": "312af8791c61800b2ce5b992b5e7db1c5ea3c9e864cd8d8aab19f397aaeee18c22ba38c5de736bf1361a6efc4574e2daa63c80a20471a30a4e97111b32d39cf1",
          "sha256": "c5c11929f2e5453c3fd93474e8934f9eca740beaa78a0a8152afe634a1aeec06",
          "sha1": "3fd96e78b80bf98b1b4b224fcabea47f435aac3a",
          "md5": "93a207ce0646fe1297ae396202327015"
        }
      ]
    }
  ]
}
