{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "5.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "enfbpwdgrngxvnw6jviw45zlyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-5.6.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-5.6.0-SNAPSHOT.jar",
          "size": 16351,
          "sha512": "f2151b3e313e0e25442426831b37d37145467b5e97c036718ba4fa51bbfe65793f74d959bc0ebbdc98b683a27dc04f779566479e3f75fe2494a3e9b5c5b22f66",
          "sha256": "be65377ed21c2afed44a12a1fa16239eb8a4b5fc3cc8df68457808e9e3b26675",
          "sha1": "f10b05cb3310a21172dfc7c34ab8779922a955fe",
          "md5": "64949f0f151fe0dee8f265726e26d3b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-5.6.0-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-5.6.0-SNAPSHOT.jar",
          "size": 16351,
          "sha512": "f2151b3e313e0e25442426831b37d37145467b5e97c036718ba4fa51bbfe65793f74d959bc0ebbdc98b683a27dc04f779566479e3f75fe2494a3e9b5c5b22f66",
          "sha256": "be65377ed21c2afed44a12a1fa16239eb8a4b5fc3cc8df68457808e9e3b26675",
          "sha1": "f10b05cb3310a21172dfc7c34ab8779922a955fe",
          "md5": "64949f0f151fe0dee8f265726e26d3b3"
        }
      ]
    }
  ]
}
