{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.7.1.jar",
          "url": "kodein-internal-gradle-plugin-8.7.1.jar",
          "size": 438523,
          "sha512": "d2f6738206b440db9ae75be1e667773ec2fd69c577064b804f9e0f6a181608a79a80e2a66b0b203f87511599c4e42df596ce79455f0ba3b733368b5275748eac",
          "sha256": "4d2f59593f44565b60a1159f4518f272835ca0e33926f02bf070b5715d35a3b9",
          "sha1": "39b9dacae3c9045b2c11ab05e3dc7b08fc6d5437",
          "md5": "cee42c4ee3a67a3cee0fd263fe6ed1ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.7.1.jar",
          "url": "kodein-internal-gradle-plugin-8.7.1.jar",
          "size": 438523,
          "sha512": "d2f6738206b440db9ae75be1e667773ec2fd69c577064b804f9e0f6a181608a79a80e2a66b0b203f87511599c4e42df596ce79455f0ba3b733368b5275748eac",
          "sha256": "4d2f59593f44565b60a1159f4518f272835ca0e33926f02bf070b5715d35a3b9",
          "sha1": "39b9dacae3c9045b2c11ab05e3dc7b08fc6d5437",
          "md5": "cee42c4ee3a67a3cee0fd263fe6ed1ba"
        }
      ]
    }
  ]
}
