{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "t4wsqpzgxbgildas67iuv3efcu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-4.0.0.jar",
          "url": "kodein-internal-gradle-plugin-4.0.0.jar",
          "size": 257447,
          "sha512": "91a11c44871ac7150367df0b533e635865327a7f4d6188b305776186be5c36d1dfb21ba18152b1048081c5729b6421a42ea0217513b8ea2186377c2d44fd1000",
          "sha256": "f188bea55b2ee4d6b955e34d33cac59b11111cb92c6ef821fff0f228aa46f33d",
          "sha1": "15fd7f36a48484111f4846fb57d13ad900cd9e51",
          "md5": "94968b25238d3759dbf3f7c86111c765"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-4.0.0.jar",
          "url": "kodein-internal-gradle-plugin-4.0.0.jar",
          "size": 257447,
          "sha512": "91a11c44871ac7150367df0b533e635865327a7f4d6188b305776186be5c36d1dfb21ba18152b1048081c5729b6421a42ea0217513b8ea2186377c2d44fd1000",
          "sha256": "f188bea55b2ee4d6b955e34d33cac59b11111cb92c6ef821fff0f228aa46f33d",
          "sha1": "15fd7f36a48484111f4846fb57d13ad900cd9e51",
          "md5": "94968b25238d3759dbf3f7c86111c765"
        }
      ]
    }
  ]
}
