{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.10.0.jar",
          "url": "kodein-internal-gradle-plugin-6.10.0.jar",
          "size": 262090,
          "sha512": "35d01811a7d65543a76495781e995b1ef4a572906e10b5f479bbd543b66d7372f563c4b4b9f9e2558e95c49aed480005ca4a69057161add4e34f6ebca39726cc",
          "sha256": "555f58eb67e613aa45fdfc0a7b01e4d409828e19c6528015695a0932de8fd6ec",
          "sha1": "e103b987abe44b517054d1142691a63d0776bf9e",
          "md5": "cdd957a17477d94e27a65ec67088041d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.10.0.jar",
          "url": "kodein-internal-gradle-plugin-6.10.0.jar",
          "size": 262090,
          "sha512": "35d01811a7d65543a76495781e995b1ef4a572906e10b5f479bbd543b66d7372f563c4b4b9f9e2558e95c49aed480005ca4a69057161add4e34f6ebca39726cc",
          "sha256": "555f58eb67e613aa45fdfc0a7b01e4d409828e19c6528015695a0932de8fd6ec",
          "sha1": "e103b987abe44b517054d1142691a63d0776bf9e",
          "md5": "cdd957a17477d94e27a65ec67088041d"
        }
      ]
    }
  ]
}
