{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "eyu6i5iatrfzfarnagjy3532lu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "0.9.18"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-3.4.1.jar",
          "url": "kodein-internal-gradle-plugin-3.4.1.jar",
          "size": 245603,
          "sha512": "d22315ff28968cae7f027ccea383f3ba9d96df244be27b829397db969b499907cb35ef4dea03ae1b77e27a883fe3e59e7822993225701642b88cd99759700882",
          "sha256": "b3d8ae70a91d3a81280cc7d6f03874f25751f11228e58690c6bfe96b3d4ff861",
          "sha1": "9a8d5d1e724d6b39da4cd73c40a2cdf63ef94a0c",
          "md5": "f24bad61cffe6e7913086a3d9ba00349"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.21"
          }
        },
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "0.9.18"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-3.4.1.jar",
          "url": "kodein-internal-gradle-plugin-3.4.1.jar",
          "size": 245603,
          "sha512": "d22315ff28968cae7f027ccea383f3ba9d96df244be27b829397db969b499907cb35ef4dea03ae1b77e27a883fe3e59e7822993225701642b88cd99759700882",
          "sha256": "b3d8ae70a91d3a81280cc7d6f03874f25751f11228e58690c6bfe96b3d4ff861",
          "sha1": "9a8d5d1e724d6b39da4cd73c40a2cdf63ef94a0c",
          "md5": "f24bad61cffe6e7913086a3d9ba00349"
        }
      ]
    }
  ]
}
