{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.11.0.jar",
          "url": "kodein-internal-gradle-plugin-6.11.0.jar",
          "size": 268656,
          "sha512": "0b5acfe1a8c8b4886f9f23006a7cac51f435c60d285d7ab6e8d3b271e7e2bb90eda08b6694bedbf8224a1724539c4945a628a7c1193a504d90daea07f189af0d",
          "sha256": "cbb4ecabe468d6390fffbb9bd02addb1dc568e80ffa30c03eb5019056103d585",
          "sha1": "101a16ea6bdb2a139cd4a7ed748346d99eef17bd",
          "md5": "6fd466602ef2ee405c9df1adcafc01c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.11.0.jar",
          "url": "kodein-internal-gradle-plugin-6.11.0.jar",
          "size": 268656,
          "sha512": "0b5acfe1a8c8b4886f9f23006a7cac51f435c60d285d7ab6e8d3b271e7e2bb90eda08b6694bedbf8224a1724539c4945a628a7c1193a504d90daea07f189af0d",
          "sha256": "cbb4ecabe468d6390fffbb9bd02addb1dc568e80ffa30c03eb5019056103d585",
          "sha1": "101a16ea6bdb2a139cd4a7ed748346d99eef17bd",
          "md5": "6fd466602ef2ee405c9df1adcafc01c9"
        }
      ]
    }
  ]
}
