{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "n3prprocvbhfjhw4zb4p3z7474"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20.2-dev-74"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.20.2-dev-74"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.4.0.jar",
          "url": "kodein-internal-gradle-plugin-6.4.0.jar",
          "size": 257433,
          "sha512": "579d8496ce3a49cf7e862630f5d19bf4596ace1bab9bdd9a5f057ec23bd5b5f8d280021627c4ad2214af017a8512cfb73281e9a3e4fa8dd884a8869a9ad30300",
          "sha256": "1504a95e645c4bcd769982fdb37077cc9770aa90201270deafa762f6b9d170f9",
          "sha1": "abb8f1e497052c2fdcb829e245fda0817901857c",
          "md5": "18fb0f1a7dfcb283363a5f9265f8f6a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20.2-dev-74"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.20.2-dev-74"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.4.0.jar",
          "url": "kodein-internal-gradle-plugin-6.4.0.jar",
          "size": 257433,
          "sha512": "579d8496ce3a49cf7e862630f5d19bf4596ace1bab9bdd9a5f057ec23bd5b5f8d280021627c4ad2214af017a8512cfb73281e9a3e4fa8dd884a8869a9ad30300",
          "sha256": "1504a95e645c4bcd769982fdb37077cc9770aa90201270deafa762f6b9d170f9",
          "sha1": "abb8f1e497052c2fdcb829e245fda0817901857c",
          "md5": "18fb0f1a7dfcb283363a5f9265f8f6a1"
        }
      ]
    }
  ]
}
