{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.gradleup.nmcp.aggregation",
          "module": "com.gradleup.nmcp.aggregation.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.17.0.jar",
          "url": "kodein-internal-gradle-plugin-8.17.0.jar",
          "size": 271743,
          "sha512": "3ab77dc66b6d2b8ce6b2d00a229877042d4ef7a6983e322955ef33c799ed1fa02b0a9e77dbac40070a067c88e11c0879a77abdb774d4e9d3c487bd2fc2537565",
          "sha256": "c0916444c95a4963d3c8a56b5a530c4873da09cf1f034c812b87febace837630",
          "sha1": "0604877a7b6aca4de4f0571c462f70d68ec772b0",
          "md5": "89d4ad934a1d67c438e515cf23e17ea1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.gradleup.nmcp.aggregation",
          "module": "com.gradleup.nmcp.aggregation.gradle.plugin",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.gradle.develocity",
          "module": "com.gradle.develocity.gradle.plugin",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.17.0.jar",
          "url": "kodein-internal-gradle-plugin-8.17.0.jar",
          "size": 271743,
          "sha512": "3ab77dc66b6d2b8ce6b2d00a229877042d4ef7a6983e322955ef33c799ed1fa02b0a9e77dbac40070a067c88e11c0879a77abdb774d4e9d3c487bd2fc2537565",
          "sha256": "c0916444c95a4963d3c8a56b5a530c4873da09cf1f034c812b87febace837630",
          "sha1": "0604877a7b6aca4de4f0571c462f70d68ec772b0",
          "md5": "89d4ad934a1d67c438e515cf23e17ea1"
        }
      ]
    }
  ]
}
