{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.5.0-kotlin-1.5-M2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2padelw4bfa4tmxyx7s4p3qlbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "size": 16498,
          "sha512": "fd4c3686e1a0827495478652530a7b0ee05b159c53fc7d2dbe66b698ad272201276999e8739867ec9dc83e959d0cec7ad74bf10257347a26d491dfb19488f0e6",
          "sha256": "fd267b8f2b173d0e69379d05b4343d20588ea3bf143583dcf03f4fa9d51b4da6",
          "sha1": "42dc9184b9814c16fccc2994b50324b085e38229",
          "md5": "db8a2e76e6e6e9ce1fcd91e2c7a28153"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.5.0-kotlin-1.5-M2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "size": 16498,
          "sha512": "fd4c3686e1a0827495478652530a7b0ee05b159c53fc7d2dbe66b698ad272201276999e8739867ec9dc83e959d0cec7ad74bf10257347a26d491dfb19488f0e6",
          "sha256": "fd267b8f2b173d0e69379d05b4343d20588ea3bf143583dcf03f4fa9d51b4da6",
          "sha1": "42dc9184b9814c16fccc2994b50324b085e38229",
          "md5": "db8a2e76e6e6e9ce1fcd91e2c7a28153"
        }
      ]
    }
  ]
}
