{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.5.0-kotlin-1.5-M2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b32l3npyn5b5bi6tzvk73kqrse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "size": 16525,
          "sha512": "d0c0ce009e4e945c9aff94ece2daea5c3991c011c3017c37efd201951e93d7b6b7cdb3b0b137b974a81e355a5a5e7ade96b598c71ca4cbc7a9792d5791759530",
          "sha256": "56a28708bed387f89591b9573baaa20e11e7d801c3ee92c47f1e22a896d2c800",
          "sha1": "6107096151b6da297fefbe09ecc4e87320c42f24",
          "md5": "d7a80fca8400cd5107844b9a5c87e319"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.5.0-kotlin-1.5-M2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "size": 16525,
          "sha512": "d0c0ce009e4e945c9aff94ece2daea5c3991c011c3017c37efd201951e93d7b6b7cdb3b0b137b974a81e355a5a5e7ade96b598c71ca4cbc7a9792d5791759530",
          "sha256": "56a28708bed387f89591b9573baaa20e11e7d801c3ee92c47f1e22a896d2c800",
          "sha1": "6107096151b6da297fefbe09ecc4e87320c42f24",
          "md5": "d7a80fca8400cd5107844b9a5c87e319"
        }
      ]
    }
  ]
}
