{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "6.18.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.18.3-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.18.3-SNAPSHOT.jar",
          "size": 16321,
          "sha512": "33ec477eac1bf787c5422f08286659ee7ee410710b3df91bd8630a76f9ddb01a4096c527974804dd0fcd5cfa4bff1e79e556cba528c8ff18fcd08599bf089a77",
          "sha256": "8838eba4f17dcf7f9cf7942810295b5868aeac8e43ce53129c6e7a7f9c65d574",
          "sha1": "8e97a5c747944b15605df8e08cd0b4b6319921b6",
          "md5": "5227c83bd2ea7cfd606e4eea24308dc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.18.3-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-6.18.3-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-settings-6.18.3-SNAPSHOT.jar",
          "size": 16321,
          "sha512": "33ec477eac1bf787c5422f08286659ee7ee410710b3df91bd8630a76f9ddb01a4096c527974804dd0fcd5cfa4bff1e79e556cba528c8ff18fcd08599bf089a77",
          "sha256": "8838eba4f17dcf7f9cf7942810295b5868aeac8e43ce53129c6e7a7f9c65d574",
          "sha1": "8e97a5c747944b15605df8e08cd0b4b6319921b6",
          "md5": "5227c83bd2ea7cfd606e4eea24308dc0"
        }
      ]
    }
  ]
}
