{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4jefjpcxlng3hcfa3jk4afg2pe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.4.1.jar",
          "url": "kodein-internal-gradle-plugin-6.4.1.jar",
          "size": 257433,
          "sha512": "9a8b87a2438502b608229c93049429ea7c0e7ba6c58f045aa44c28ce3ba4305b62c688bd88c072800a631d18b5f7c5b90ab607ac556117c668d6398ce4b6e098",
          "sha256": "d3db9a556ce2a456ffa4faa1565c0abeaa4240d60bef40762ee8e073dfd3cc6e",
          "sha1": "4fa5fc0db8518b9dea87b6dede75ae71ce8afb3d",
          "md5": "69f9f37700cde351414ff74ca6981451"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.4.1.jar",
          "url": "kodein-internal-gradle-plugin-6.4.1.jar",
          "size": 257433,
          "sha512": "9a8b87a2438502b608229c93049429ea7c0e7ba6c58f045aa44c28ce3ba4305b62c688bd88c072800a631d18b5f7c5b90ab607ac556117c668d6398ce4b6e098",
          "sha256": "d3db9a556ce2a456ffa4faa1565c0abeaa4240d60bef40762ee8e073dfd3cc6e",
          "sha1": "4fa5fc0db8518b9dea87b6dede75ae71ce8afb3d",
          "md5": "69f9f37700cde351414ff74ca6981451"
        }
      ]
    }
  ]
}
