{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "unaabr4ctrghliajts2ackrcri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "0.9.18"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-3.4.3.jar",
          "url": "kodein-internal-gradle-plugin-3.4.3.jar",
          "size": 244451,
          "sha512": "b6e6a20b746502d1ad414345eb3b9e154e74e7685d092187fd29b0126dbc4080c5fce0026e1802b3436c58c024e67807b3533548f0a7e86d227c3b9d656fdd80",
          "sha256": "f4f10fc91d7ea633a6844b2c7c8b3ddfcb470c31b668f34cb5384dfdbde9cdfa",
          "sha1": "2c9fa35c190e6dc3d538d944da676a93e5c3b26c",
          "md5": "5df33c4044618b2cb52f3269a0422c66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.21"
          }
        },
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "0.9.18"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-3.4.3.jar",
          "url": "kodein-internal-gradle-plugin-3.4.3.jar",
          "size": 244451,
          "sha512": "b6e6a20b746502d1ad414345eb3b9e154e74e7685d092187fd29b0126dbc4080c5fce0026e1802b3436c58c024e67807b3533548f0a7e86d227c3b9d656fdd80",
          "sha256": "f4f10fc91d7ea633a6844b2c7c8b3ddfcb470c31b668f34cb5384dfdbde9cdfa",
          "sha1": "2c9fa35c190e6dc3d538d944da676a93e5c3b26c",
          "md5": "5df33c4044618b2cb52f3269a0422c66"
        }
      ]
    }
  ]
}
