{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "8.7.0-kotlin-2.0.0-RC3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0-RC3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.0.0-RC3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.jar",
          "size": 438523,
          "sha512": "a8ffb1565e70b054b6e35c46c9b1c3a8be9c1d8789cd4f4b3533f65713d0a3d42dc974d38de11c359460d53a28a08d37d4576118b3d5f70ad584d168ec329bcf",
          "sha256": "520a921ca75254f4109a3d5a77c00f84ed6a7fed313ca54eda6899e6e6ddc5ba",
          "sha1": "2712b3d820ae1016153f49e93381551ccb9d8270",
          "md5": "4d03e2e1e82e850d64d99f496164a3a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0-RC3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0-RC3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "2.0.0-RC3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.gradle.enterprise",
          "module": "com.gradle.enterprise.gradle.plugin",
          "version": {
            "requires": "3.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-plugin-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.jar",
          "size": 438523,
          "sha512": "a8ffb1565e70b054b6e35c46c9b1c3a8be9c1d8789cd4f4b3533f65713d0a3d42dc974d38de11c359460d53a28a08d37d4576118b3d5f70ad584d168ec329bcf",
          "sha256": "520a921ca75254f4109a3d5a77c00f84ed6a7fed313ca54eda6899e6e6ddc5ba",
          "sha1": "2712b3d820ae1016153f49e93381551ccb9d8270",
          "md5": "4d03e2e1e82e850d64d99f496164a3a3"
        }
      ]
    }
  ]
}
