{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-settings",
    "version": "3.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dcr5kwd6ifa7rlsjm5x5dius4u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-settings-3.4.2.jar",
          "url": "kodein-internal-gradle-settings-3.4.2.jar",
          "size": 13908,
          "sha512": "45dea5fca6ef476394a23c891f3f53c13723cd0dabdf48ea88613b531225297494227b04478b311a40639a987ebdc20ff7babec351c22e17d556950f5038e6e3",
          "sha256": "3502dc9adc56e4034af9e690e666d0a63f06915447a542790c4358ad95886e11",
          "sha1": "597f86a495f4ce0bd66af4ec06e84f869640f3a1",
          "md5": "0e336d4741e39e885159efd68a0fe9a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-settings-3.4.2.jar",
          "url": "kodein-internal-gradle-settings-3.4.2.jar",
          "size": 13908,
          "sha512": "45dea5fca6ef476394a23c891f3f53c13723cd0dabdf48ea88613b531225297494227b04478b311a40639a987ebdc20ff7babec351c22e17d556950f5038e6e3",
          "sha256": "3502dc9adc56e4034af9e690e666d0a63f06915447a542790c4358ad95886e11",
          "sha1": "597f86a495f4ce0bd66af4ec06e84f869640f3a1",
          "md5": "0e336d4741e39e885159efd68a0fe9a6"
        }
      ]
    }
  ]
}
