{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "5.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "bw7tw6ot5vfqramkztvezztdai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.3.3.jar",
          "url": "kodein-internal-gradle-plugin-5.3.3.jar",
          "size": 250757,
          "sha512": "86ff1a432b65a2183a1c9f02cca8763b25462dd9668b561cd753fb06be668be50f9e0768852d30ff1e2d8e75634d9e1152c1a6fa4545c84ec686498c163df244",
          "sha256": "55f30a9137d6dc63105a71dda1c9602a53a9ad1be9f81223a338f09feedb9433",
          "sha1": "9ac2e163f1f1c51c316bfdeadddb0c9106fd0bb8",
          "md5": "cbaec733afd73b08a32dcd901b4d5b61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-5.3.3.jar",
          "url": "kodein-internal-gradle-plugin-5.3.3.jar",
          "size": 250757,
          "sha512": "86ff1a432b65a2183a1c9f02cca8763b25462dd9668b561cd753fb06be668be50f9e0768852d30ff1e2d8e75634d9e1152c1a6fa4545c84ec686498c163df244",
          "sha256": "55f30a9137d6dc63105a71dda1c9602a53a9ad1be9f81223a338f09feedb9433",
          "sha1": "9ac2e163f1f1c51c316bfdeadddb0c9106fd0bb8",
          "md5": "cbaec733afd73b08a32dcd901b4d5b61"
        }
      ]
    }
  ]
}
