{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-version-catalog",
    "version": "8.7.0-kotlin-2.0.0-RC3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-version-catalog-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.toml",
          "url": "kodein-internal-gradle-version-catalog-8.7.0-kotlin-2.0.0-RC3-SNAPSHOT.toml",
          "size": 1719,
          "sha512": "a008cc705cdd10c17c83b889307364197754ccf77f38dfec836dcaed2bd8d13e9a619b12cd1c31f19b1f9deae4f89bab381d32fee3dbe5fa017de283dbd1cfe9",
          "sha256": "6a4b2e34b6f45c35516e55ca11ad712778094b5bce5e0b9f4a5305af15dace62",
          "sha1": "be44dd4e23fd88f942dbe24d0a0f080498c7c214",
          "md5": "2e596e4277d30d6bb292052f6aefc365"
        }
      ]
    }
  ]
}
