{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "3.6.1-1.4-M2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "s7ctrozaqvdn5e25msdi3j4ozm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.6.1-1.4-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4-M2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "0.9.18"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-3.6.1-1.4-M2.jar",
          "url": "kodein-internal-gradle-plugin-3.6.1-1.4-M2.jar",
          "size": 252361,
          "sha512": "ed8f4543bd5298d0d81bb81889a33bc4fef258c695914695420794ed4612b3d7b6efb7eb87cc938270016c0c9c07e9c9c9e70cbd051b1f017fcb54735132c6ae",
          "sha256": "60c29c65c984fc162ba7e07d0f23b91247a96dc0eb95416303de7d1e07d82d5f",
          "sha1": "6ffb27a52b7f1a188872bbeefc9ff9e829203401",
          "md5": "7475e66e405e2980ff367e71d9a6965a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "3.6.1-1.4-M2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4-M2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "0.9.18"
          }
        },
        {
          "group": "digital.wup",
          "module": "android-maven-publish",
          "version": {
            "requires": "3.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-3.6.1-1.4-M2.jar",
          "url": "kodein-internal-gradle-plugin-3.6.1-1.4-M2.jar",
          "size": 252361,
          "sha512": "ed8f4543bd5298d0d81bb81889a33bc4fef258c695914695420794ed4612b3d7b6efb7eb87cc938270016c0c9c07e9c9c9e70cbd051b1f017fcb54735132c6ae",
          "sha256": "60c29c65c984fc162ba7e07d0f23b91247a96dc0eb95416303de7d1e07d82d5f",
          "sha1": "6ffb27a52b7f1a188872bbeefc9ff9e829203401",
          "md5": "7475e66e405e2980ff367e71d9a6965a"
        }
      ]
    }
  ]
}
