{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-versions",
    "version": "6.5.0-kotlin-1.5-M2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2padelw4bfa4tmxyx7s4p3qlbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "size": 3161,
          "sha512": "6b445911cf0312e4190a7430dda93130258abbfce4ce12d1732f8a69cab0698fbdec143fcd377cbb1a264091953b4e52cd883062889da8f2eb5dc55411f3edef",
          "sha256": "48f7e367976e064b23e07112d876b18126ff30129d7e07d7f4ddf454cf4e7cf5",
          "sha1": "12d94fb53d897e0352ddc1a823f9e7daf2fe1b91",
          "md5": "689fb2a8564ee1940a02b50f2928d1fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kodein-internal-gradle-versions-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "url": "kodein-internal-gradle-versions-6.5.0-kotlin-1.5-M2-SNAPSHOT.jar",
          "size": 3161,
          "sha512": "6b445911cf0312e4190a7430dda93130258abbfce4ce12d1732f8a69cab0698fbdec143fcd377cbb1a264091953b4e52cd883062889da8f2eb5dc55411f3edef",
          "sha256": "48f7e367976e064b23e07112d876b18126ff30129d7e07d7f4ddf454cf4e7cf5",
          "sha1": "12d94fb53d897e0352ddc1a823f9e7daf2fe1b91",
          "md5": "689fb2a8564ee1940a02b50f2928d1fc"
        }
      ]
    }
  ]
}
