name: Release

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build
        run: ./gradlew build
      - name: build & publish
        env:
          GITHUB_USER: ${{ secrets.GIT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_PASSWORD }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
