name: Release

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: kosi-libs/kodein-internal-github-actions/setup@main
        with:
          konan: false
      - name: build locally
        run: ./gradlew --scan publishToMavenLocal
      - name: Copy local build
        run: ./gradlew --scan gitPublishCopy
      - name: Publish to mvn-repo
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: ./gradlew --scan gitPublishPush
