{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.internal.gradle",
    "module": "kodein-internal-gradle-plugin",
    "version": "6.20.2-kotlin-1.7.20-RC",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.20.2-kotlin-1.7.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.7.20-RC"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.20.2-kotlin-1.7.20-RC.jar",
          "url": "kodein-internal-gradle-plugin-6.20.2-kotlin-1.7.20-RC.jar",
          "size": 274270,
          "sha512": "b78d07624652a9ac5b7c551d9cb0672f0685ce6c0bbcf2a5b858d04f13481782b96b131e635fac4d750a03c0c28e46a250fc6ccaede87b2c5ba804cef68fc294",
          "sha256": "4dd71c3e6a980cebe28ec4c5dadd57bd7d3bf4ba5b39338839a5996aff63bbd8",
          "sha1": "66fa6afa4b5eebf8f77226ded190cc26a19c100b",
          "md5": "aaf24aac6460f4ff6b9e00106708d1d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20-RC"
          }
        },
        {
          "group": "org.kodein.internal.gradle",
          "module": "kodein-internal-gradle-versions",
          "version": {
            "requires": "6.20.2-kotlin-1.7.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.7.20-RC"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "0.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-internal-gradle-plugin-6.20.2-kotlin-1.7.20-RC.jar",
          "url": "kodein-internal-gradle-plugin-6.20.2-kotlin-1.7.20-RC.jar",
          "size": 274270,
          "sha512": "b78d07624652a9ac5b7c551d9cb0672f0685ce6c0bbcf2a5b858d04f13481782b96b131e635fac4d750a03c0c28e46a250fc6ccaede87b2c5ba804cef68fc294",
          "sha256": "4dd71c3e6a980cebe28ec4c5dadd57bd7d3bf4ba5b39338839a5996aff63bbd8",
          "sha1": "66fa6afa4b5eebf8f77226ded190cc26a19c100b",
          "md5": "aaf24aac6460f4ff6b9e00106708d1d6"
        }
      ]
    }
  ]
}
